version: '3.8'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: 19112002
            POSTGRES_USER: postgres
            POSTGRES_DB: image_captioning
        expose:
            - "5433" # Publishes 5432 to other containers but NOT to host machine
        ports:
            - "5433:5433"
        volumes:
          - ./testdb:/db_mount
        command: -p 5433
        networks:
          - app-network

    backend:
        build:
          context: ./server_mvc
          dockerfile: Dockerfile
        ports:
          - "5001:5000"
        environment:
          - FLASK_ENV=development
        depends_on:
          - db
        networks:
          - app-network

          
    frontend:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
          - backend
        networks:
          - app-network

networks:
  app-network:
    driver: bridge