# Use the official Python image as a base
FROM python:3.11-bullseye

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY ./requirements_docker.txt .

# Install dependencies
RUN pip install -U flask-cors
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install -r requirements_docker.txt
# Copy the rest of the application code to the working directory
COPY . .
COPY ./.env_docker ./.env

# Set environment variables for Flask
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

EXPOSE 5001

RUN pip3 install python-dotenv
# Set the command to run the Flask app
CMD ["python", "app.py"]
