# Use the official Node.js image as a base
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the React application
RUN npm run build

# Serve the built application using a simple HTTP server
RUN npm install -g serve

# Set the command to run the server
CMD ["serve", "-s", "build"]

# Expose the port the app runs on
EXPOSE 3000
